### ISSUE TITLE
temporarily use the `chunk` subcommand to chunk it with a appropriate size (< 65535).

### ISSUE THREAD

**Issue by sip123a** [wjwei-handsome/wgatools#16]
Thank you for developing the software, which is very easy to use. There is a small error, that is, opening the ```wgatools tview maf ```command cannot quickly locate the location you want to view.

``` ERROR scroll out of u16 range, This error is due to the scrolling limit of `ratatui`(https://github.com/ratatui-org/ratatui/issues/399). You can temporarily use the `chunk` subcommand to chunk it with a appropriate size (< 65535).```

I checked ratatui's issue, but I couldn't solve it effectively (I'm not familiar with ratatui). Is there any way to solve it quickly and effectively?
 Targeting values ​​cannot be deleted at the same time. as follows:
![image](https://github.com/user-attachments/assets/dda03b3b-781d-4ba6-8265-0e87e483bc8a)

thank you again!

**Comment by sip123a** [comment]
Thank you for your quick reply. I can easily check the comparison of each paragraph after using ```chunk```. The situation is as follows:
![image](https://github.com/user-attachments/assets/01591576-64e4-46cb-966b-5be6382f4e5f)


 It’s just that the location information still cannot be changed. It may be a limitation of the software that visualization relies on.

Best regards

**Comment by wjwei-handsome** [comment]
I'm glad it helped you!

But for the problem of location modification. I think the problem is your keyboard mapping and not the software. If so, can you share your shell configuration(like `.bash_profile` or `.bashrc`) or the Terminal emulator(mobaterm or xterm or iterm2 ....)? 

I believe this can be solved!

Best regards,
wenjie

**Comment by wjwei-handsome** [comment]
refer to this: https://www.linuxquestions.org/questions/linux-newbie-8/backspace-makes-a-%5Eh-character-4175671214/

**Comment by sip123a** [comment]
Wow，yes, you are right. This isn't software problem, I refer to https://www.linuxquestions.org/questions/linux-newbie-8/backspace-makes-a-%5Eh-character-4175671214/.I used ```ctrl+backspace``` to delete successfully, and I can manually enter the positioning and quickly obtain the alignment of each site. Thanks again for the reference information, it's very useful.

![image](https://github.com/user-attachments/assets/35b9135f-2dbc-4aac-9bfb-b9898235ea38)
I hope other users can effectively use and refer to this issue to effectively solve the problem.
