### ISSUE TITLE
Lower case for nucleotides results in error

### ISSUE THREAD

**Issue by ebioman** [wjwei-handsome/wgatools#3]
Hi
Appreciating def. the effort of writing these tools in rust :)
Small issue which I encountered today while testing paf2maf is the fact that lower nucleotide cases in query or target will actually lead to an error:

```bash
wgatools paf2maf --query FF_SIM_1_query.fa --target  FF_SIM_1_target.fa test.paf -o /tmp/test.maf -r 
2023-12-29T10:07:54.434994554+01:00 WARN file /tmp/test.maf exist, will rewrite it
2023-12-29T10:07:54.456604913+01:00 INFO start write file: `/tmp/test.maf`
2023-12-29T10:08:05.112005605+01:00 ERROR Invalid Base: `c`
```

Switching all my nucleotides to upper case fixed it. But I think that is something which you might encounter quite frequently and what should be fixed.

**Comment by wjwei-handsome** [comment]
Hi @ebioman 
Thanks for catching this!  
I have fixed this error, please clone newest repo or install again :)
Please let me know if this can help you.
