### ISSUE TITLE
About installing

### ISSUE THREAD

**Issue by socialhang** [wjwei-handsome/wgatools#9]
@wjwei-handsome 

I am writing to express my keen interest in trying out wgatools. However, I am encountering difficulties installing it from GitHub. I am wondering if you happen to have a compiled version for CentOS 7 or a mature Docker image available?

Your assistance in this matter would be greatly appreciated.

Thank you for your attention to this inquiry.

Best regards,

**Comment by wjwei-handsome** [comment]
We provide a nix-based and docker image installation method: https://github.com/wjwei-handsome/wgatools?tab=readme-ov-file#nix

Coincidentally, I also have a centos7 working environment 😄 , and I successfully compiled the executable:

[wgatools.gz](https://github.com/wjwei-handsome/wgatools/files/14820709/wgatools.gz)

Just download and  gunzip it.

Best wishes.

**Comment by wjwei-handsome** [comment]
Hi @socialhang 

Please let me know if there are any problems about installing :)

**Comment by socialhang** [comment]
Everythings is ok!
